import {numeric} from './observed-core.mjs';
export function pumpRows(groups,now=Date.now()){
 return groups.flatMap(g=>(g.rows||[]).flatMap(r=>{const match=String(r.site_timestamp_station).match(/^\/Date\((\d+)\)\/$/),time=match?Number(match[1]):null,lat=numeric(r.latitude),lon=numeric(r.longitude),count=numeric(r.pump_count);if(!Number.isInteger(r.pumpStation_id)||!time||time>now+60000||now-time>86400000||!r.pumpStation_name||lat===null||lon===null||lat<13||lat>15||lon<99||lon>102||!Number.isInteger(count)||count<0||count>50)return [];
 const connected=r.rtu_status===true||r.rtu_status===1,stale=now-time>900000;
 const machines=Array.from({length:count},(_,i)=>{const status=r['pump_status'+(i+1)],trip=r['pump_trip_status'+(i+1)];return !connected||stale?'ไม่ยืนยัน':trip===true?'ขัดข้อง':trip===false&&status===1?'ทำงาน':trip===false&&status===0?'หยุด':'ไม่ทราบ';});
 const gates=Array.from({length:Math.min(4,Math.max(0,numeric(r.pump_gate_count)||0))},(_,i)=>connected&&!stale?numeric(r['pump_gate0'+(i+1)]):null);
 return [{gates,id:g.group+':'+r.pumpStation_id,name:r.pumpStation_name,code:r.pumpStation_code,district:r.district_name,time,lat,lon,count,connected,stale,machines,group:g.group,stationId:r.pumpStation_id}];}));
}
export function initPumps({map,json}){
 const $=id=>document.getElementById(id),fmt=t=>new Date(t).toLocaleString('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'short',timeStyle:'short'});let rows=[],raw=[],chosen=null,lastTick=0;
 const layer=map&&L.layerGroup();
 function detail(r){chosen=r.id;$('livePumpSelect').value=r.id;const target=$('pumpLiveDetail');target.replaceChildren();const title=document.createElement('b');title.textContent=r.name;target.append(title);const meta=document.createElement('p');meta.className='muted';meta.textContent=`${r.code} · ${r.district} · ${fmt(r.time)}${r.stale?' · ข้อมูลเก่า':''}${!r.connected?' · ขาดการติดต่อ':''}`;target.append(meta);const list=document.createElement('div');list.className='machine-grid';r.machines.forEach((s,i)=>{const b=document.createElement('span');b.className=s==='ทำงาน'?'machine-running':s==='ขัดข้อง'?'machine-fault':'machine-idle';b.textContent=`${i+1} ${s}`;list.append(b);});target.append(list);if(r.gates.length){const gate=document.createElement('p');gate.textContent='ระยะเปิดประตู: '+r.gates.map((v,i)=>`บาน ${i+1}: ${v===null?'ไม่ยืนยัน':v.toFixed(2)+' ม.'}`).join(' · ');target.append(gate);}const a=document.createElement('a');a.href=`https://weather.bangkok.go.th/${r.group}/StationDetail?id=${r.stationId}`;a.target='_blank';a.rel='noopener noreferrer';a.textContent='ดูสถานีที่สำนักการระบายน้ำ ↗';target.append(a);}
 function render(){layer?.clearLayers();const eligible=rows.filter(r=>!r.stale&&r.connected),running=eligible.filter(r=>r.machines.includes('ทำงาน'));$('pumpSummary').textContent=`${running.length} สถานีมีเครื่องทำงาน / ${eligible.length} สถานีที่ติดต่อได้และไม่เกิน 15 นาที · รับ ${rows.length} สถานี`;
 const prev=chosen;$('livePumpSelect').replaceChildren(...rows.map(r=>new Option(r.name,r.id)));const r=rows.find(r=>r.id===prev)||running[0]||rows[0];if(r)detail(r);else{$('pumpLiveDetail').textContent='ไม่มีสถานะเครื่องที่ใช้ได้จากต้นทาง';chosen=null;}
 if(map&&$('livePumpToggle').checked){layer.addTo(map);for(const r of rows){const color=r.stale||!r.connected?'#8d9aa6':r.machines.includes('ขัดข้อง')?'#ff6275':r.machines.includes('ทำงาน')?'#6bf0ab':'#76b5de';const tip=document.createElement('span');tip.textContent=r.name;L.circleMarker([r.lat,r.lon],{radius:8,color:'#132937',weight:2,fillColor:color,fillOpacity:1}).addTo(layer).bindTooltip(tip).on('click',()=>detail(r));}}else if(map&&layer)map.removeLayer(layer);
 }
 $('livePumpSelect').onchange=()=>{const r=rows.find(r=>r.id===$('livePumpSelect').value);if(r){detail(r);map?.setView([r.lat,r.lon],14);}};$('livePumpToggle').onchange=render;
 return {async refresh(){try{const d=await json('/api/pumps');raw=d.groups||[];rows=pumpRows(raw);render();$('pumpSourceStatus').textContent=`ข้อมูลเผยแพร่ กทม. · ตรวจ ${fmt(Date.now())}${raw.some(g=>g.error)?' · บางระบบไม่ตอบสนอง':''}`;}catch{raw=[];rows=[];render();$('pumpSourceStatus').textContent='เชื่อมข้อมูลปั๊มไม่ได้';}},tick(){if(Date.now()-lastTick>60000){lastTick=Date.now();rows=pumpRows(raw);render();}}};
}
